### PR TITLE
Changed time.clock() to time.perf_counter()

### PR DESCRIPTION
**Pull request by TonichaC**
Clock has been removed from python 3.8 onwards

### CODE REVIEW

**Comment by ericastor** [comment]
Since time.perf_counter() is new in v3.3, can we add logic to switch which interface we use depending on the version? I'd like to keep supporting Python 2.7 for at least a little while longer.

**Comment by ericastor** [comment]
Thanks for the version control! Just as a minor thing: I don't think this will report accurate times as currently written? I think you want `timekeeper = time.time`, not `timekeeper = time.time()`, and then to call it via `timekeeper()` rather than `timekeeper`.

**Comment by TonichaC** [comment]
This can be changed but I don't actually think it makes a difference. I've tested both individually and they seem to do the same thing

**Comment by ericastor** [comment]
Strange... it should work out that `timekeeper = time.time()` assigns an integer to `timekeeper`. So you should end up with the same time regardless of delays, meaning you'd end up with 0 elapsed time measured always. Can you confirm this isn't happening? (because that sounds like a bug in Python.)

**Pull request merged**
